version: "3.7"
services:
    playground:
        image: rust-lambda-example.playground
        container_name: rust-lambda-example.playground
        build:
            context: ./
            target: playground
        volumes:
            - type: bind
              source: ./
              target: /app
        stdin_open: true
        tty: true
        network_mode: host # I can't be bothered to set up port forwarding for Netlify's elaborate setup, so forward everything!
